services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=taskmanager
    ports:
      - "5432:5432"
    volumes:
      - db-vol:/var/lib/postgresql/data

volumes:
  db-vol:


