services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=taskmanager
    ports:
      - "5432:5432"
    volumes:
      - db-vol:/var/lib/postgresql/data

#  taskmanager:
#    container_name: taskmanager
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskmanager
#    restart: unless-stopped
#    depends_on:
#      - postgres

volumes:
  db-vol:


