spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    open-in-view: false

kafka-config:
  bootstrap-servers: localhost:9092
  topic: task-status-updated-events-topic
  number-of-partitions: 3
  replication-factor: 3
  min-insync-replicas: 2
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retry-backoff-ms: 1000
    request-timeout-ms: 10000
    delivery-timeout-ms: 12000
    batch-size: 16384
    linger-ms: 10
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: task-status-updated-events
    trusted-packages: ru.michaelshell.taskmanager.model.event
